#!/bin/bash

cmd_default() {

	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	require_remote_branch "$ORIGIN/$MERGETARGET"

	echo "Rebase with branch \"$ORIGIN/$MERGETARGET\""

	git fetch $ORIGIN && \
	git rebase -p $ORIGIN/$MERGETARGET

}

cmd_help() {
	
	echo "git lava update [<base>]"
	echo
	echo "Perform a rebase, pulling in changes from the remote base branch."

}