#!/bin/bash
cmd_default() {

	local DIFF=0

	if [ "$1" = "-d" ]; then
		DIFF=1; shift
	fi

	local BRANCHNAME=$(current_branch)
	local MERGETARGET=$(local_merge_target $BRANCHNAME || echo master)
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	if [ $DIFF -eq 1 ]; then
		git diff "$ORIGIN/$MERGETARGET..." "$@"
	else
		git log "$ORIGIN/$MERGETARGET.." "$@"
	fi
	
}

cmd_help() {

	echo "git lava survey [-d]"
	echo
	echo "Show commits on current branch that don't exist on the base branch."
	echo "Optional `-d` flag will show diff. Any extra arguments are passed"
	echo "to git log or git diff."

}