#!/bin/bash

cmd_default() {

	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	require_remote_branch "$ORIGIN/$MERGETARGET"

	echo "Interactive rebase with branch '$ORIGIN/$MERGETARGET'"

	git rebase -i $ORIGIN/$MERGETARGET

}

cmd_help() {

	echo "git lava ir [<base>]"
	echo
	echo "Perform an interactive rebase against the remote base branch."

}