#!/bin/bash

cmd_ir() {

	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	require_remote_branch "$ORIGIN/$MERGETARGET"

	echo "Interactive rebase with branch \"$ORIGIN/$MERGETARGET\""

	git rebase -i $ORIGIN/$MERGETARGET

}