#!/bin/bash
#
# git-lava
#
# Usage:
# git lava diverge
# git lava converge -d

export LAVA_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

. "$LAVA_DIR/git-lava-common"

SUBCOMMAND="$1"; shift

if [ ! -e "$LAVA_DIR/git-lava-$SUBCOMMAND" ]; then
	exit 1
fi

. "$LAVA_DIR/git-lava-$SUBCOMMAND"

cmd_$SUBCOMMAND "$@"