#!/bin/bash
#
# git-lava

export LAVA_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

usage() {
	echo "usage: git lava <subcommand>"
	echo
	echo "Subcommands:"
	echo "   diverge    Make a new branch that remembers its base branch."
	echo "   converge   Merge current branch into base branch."
	echo "   erupt      Converge and push base branch."
	echo "   expose     Push new local branch to remote for collaboration."
	echo "   melt       Iteractive rebase against base branch."
	echo "   survey     View new commits in current branch."
	echo "   flow       Rebase new changes on base branch into current branch."
	echo "   base       Get base branch of current or specified branch."
	echo
	echo "Type \"git lava <subcommand> help\" for more help on specific commands."
}

. "$LAVA_DIR/git-lava-common"

SUBCOMMAND="$1"; shift

if [ ! -e "$LAVA_DIR/git-lava-$SUBCOMMAND" ]; then
	usage
	exit 1
fi

. "$LAVA_DIR/git-lava-$SUBCOMMAND"

SUBACTION="default"
if [ "$1" = "help" ]; then
	SUBACTION="help"; shift
fi
if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
	warn "Unknown subcommand: '$SUBACTION'"
	usage
	exit 1
fi

# run the specified action
cmd_$SUBACTION "$@"