#!/bin/bash

cmd_default() {
	
	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	run_hook "pre-lava-converge"

	require_local_branch $MERGETARGET
	require_remote_branch "$ORIGIN/$MERGETARGET"

	echo -e "Merging with branch '$MERGETARGET'"

	git lava update $MERGETARGET && \
	git checkout $MERGETARGET && \
	git merge $ORIGIN/$MERGETARGET && \
	git merge $BRANCHNAME

}

cmd_help() {
	
	echo "git lava converge [<base>]"
	echo
	echo "Update the current branch and merge it into the base branch. Defaults"
	echo "to the base branch saved by git lava diverge or master."

}