#!/bin/bash
cmd_default() {

	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	git log "$ORIGIN/$MERGETARGET.."
	
}

cmd_help() {

	echo "git lava log [<base>]"
	echo
	echo "Show commits on current branch that don't exist on the base branch."

}