#!/bin/bash

cmd_converge() {
	
	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	require_local_branch $MERGETARGET
	require_remote_branch "$ORIGIN/$MERGETARGET"

	echo -e "Merging with branch '$MERGETARGET'"

	. "$LAVA_DIR/git-lava-update"

	cmd_update && \
	git checkout $MERGETARGET && \
	git merge $ORIGIN/$MERGETARGET && \
	git merge $BRANCHNAME

}