#!/bin/bash

cmd_default() {
	
	local FLAGS

	while getopts m OPTION
	do
		case $OPTION in
			m)	FLAGS="--no-ff";;
		esac
	done

	# Reset $@
	shift `echo $OPTIND-1 | bc`

	local BRANCHNAME=$(current_branch)
	local MERGETARGET=${1:-$(local_merge_target $BRANCHNAME || echo master)}
	local ORIGIN=$(branch_origin $MERGETARGET || echo origin)

	run_hook "pre-lava-converge"

	require_local_branch $MERGETARGET
	require_remote_branch "$ORIGIN/$MERGETARGET"

	echo -e "Merging with branch '$MERGETARGET'"

	if [ ! "$FLAGS" ]; then
		git lava flow $MERGETARGET
	fi
	git checkout $MERGETARGET && \
	git merge $ORIGIN/$MERGETARGET && \
	git merge $FLAGS $BRANCHNAME

}

cmd_help() {
	
	echo "git lava converge [-m] [<base>]"
	echo
	echo "Update the current branch and merge it into the base branch. Defaults"
	echo "to the base branch saved by git lava diverge or master. Use optional"
	echo "-m flag to force a merge commit."

}