#!/bin/bash

cmd_flow() {

	local DELETE=0

	while getopts d OPTION
	do
		case $OPTION in
			d)	DELETE=1;;
		esac
	done

	# Reset $@
	shift `echo $OPTIND-1 | bc`

	# if [ $DELETE = "1" ]; then
	# 	git branch -d $BRANCHNAME
	# fi

}