#!bash

_git_lava() {
	local subcommands="flow diverge converge melt erupt examine base expose"

	local subcommand="$(__git_find_on_cmdline "$subcommands")"
	if [ -z "$subcommand" ]; then
		__gitcomp "$subcommands"
		return
	fi

	case "$subcommand" in
	converge)
		_git_checkout
		return
		;;
	flow)
		_git_checkout
		return
		;;
	diverge)
		_git_checkout
		return
		;;
	melt)
		_git_checkout
		return
		;;
	erupt)
		_git_checkout
		return
		;;
	examine)
		_git_checkout
		return
		;;
	*)
		COMPREPLY=()
		;;
	esac
}

complete -o nospace -F _git_lava 'git lava'